version: "3"
services:
  myportfolio:
  container_name: myportfolio
  build: .
  restart: always
  env_file:
  - . env
  environment:
  - FLASK_ENV=development
  ports:
  - "5000:5000"
  volumes:
  - .: /myportfolio
  depends_on :
  - mysql

mysql:
  container_name: mysql
  image: mariadb
  restart: always
  env file:
  - . env
volumes:
  mydatabase: